name: Update Trending Footballers

on:
  schedule:
    # Run daily at 6 AM UTC to capture global overnight activity
    - cron: '0 6 * * *'  # 06:00 UTC (captures overnight matches and morning reactions)
  workflow_dispatch:

jobs:
  update-trending:
    runs-on: ubuntu-latest
    env:
      FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
      PROXY_LIST: ${{ secrets.PROXY_LIST }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install 'urllib3<2.0.0'
          pip install requests
          pip install pytrends

      - name: Update trending data
        run: python scripts/trending_footballers.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/trending_footballers.csv public/last_update.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update trending footballers" && git push) 