name: Update Trending Footballers

on:
  schedule:
    # Run daily at 2 AM UTC to capture global overnight activity
    - cron: '0 2 * * *'  # 02:00 UTC (captures overnight matches and morning reactions)
  workflow_dispatch:

jobs:
  update-trending:
    runs-on: ubuntu-latest
    env:
      FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
      PROXY_LIST: ${{ secrets.PROXY_LIST }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Update trending footballers
        run: python scripts/trending_footballers.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/preprocessed_players.json public/trending_footballers.json public/last_update.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update trending footballers" && git push) 