name: Update Player News

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true  # Enable Git LFS
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gnews
        pip install llama-cpp-python
    
    - name: Run news fetching script
      run: python scripts/fetch_player_news.py
    
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add public/player_news.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update player news data" && git push) 