name: Update Player News

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gnews
        pip install llama-cpp-python
    
    - name: Download LLM model
      run: |
        mkdir -p models
        curl -L https://huggingface.co/TheBloke/Llama-3.2-3B-Instruct-GGUF/resolve/main/llama-3.2-3b-instruct.Q4_K_M.gguf -o models/Llama-3.2-3B-Instruct-Q4_K_M.gguf
    
    - name: Run news fetching script
      run: python scripts/fetch_player_news.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add public/player_news.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update player news data" && git push) 